### ISSUE TITLE
Only the framework gets loaded

### ISSUE THREAD

**Issue by Zemogiter** [solidDoWant/Planetbase-Framework#11]
[output_log.txt](https://github.com/solidDoWant/Planetbase-Framework/files/7890922/output_log.txt)
List of mods in `Documents\Planetbase\Mods`:
```
 AutoConnections
 BuildingAligner
 ComponentManager
 MoreColonistsSettings
 Planetbase Framework
 StorageGuruData
 _Utilities
 AlmostNoSpares.dll
 AutoRotateBuildings.dll
 BetterHours.dll
 CharacterCam.dll
 EternalBot.dll
 morecolonists.dll
 MoreEmbeddedRecources.dll
 Redirector.dll
 StorageGuru.dll
```

**Comment by solidDoWant** [comment]
The mods in your list are not compatible with this framework. Due to lack of project traction and limited community interest in general I do not currently plan on adding support for jpfarias's modpatcher mods.

**Comment by NeoRider7** [comment]
> [output_log.txt](https://github.com/solidDoWant/Planetbase-Framework/files/7890922/output_log.txt) List of mods in `Documents\Planetbase\Mods`:
> 
> ```
>  AutoConnections
>  BuildingAligner
>  ComponentManager
>  MoreColonistsSettings
>  Planetbase Framework
>  StorageGuruData
>  _Utilities
>  AlmostNoSpares.dll
>  AutoRotateBuildings.dll
>  BetterHours.dll
>  CharacterCam.dll
>  EternalBot.dll
>  morecolonists.dll
>  MoreEmbeddedRecources.dll
>  Redirector.dll
>  StorageGuru.dll
> ```

**### Main PROBLEMS OF INSTALLING MODS.**

If you encounter problems installing mods or engines for working with mods (Patcher, Redirector, Utilities, etc.),
then most likely the problem lies in the following:

### **1) .Net Framework 3.5.**
Make sure that "Windows .Net Framework 3.5" is installed on your computer or its functions are activated.

### **2) the files in the Planetbase directory are marked as _read-only_.**
The problem many people have with installing the Patcher is that some files in the Planetbase directory are marked read-only.
Thus, Mod Patcher (Patcher-1) cannot do its job.
The solution is to go into the Planetbase directory, then select everything (both directories and files) and go to "properties".
You will see in the properties that the "Attribute" field is marked in black.
So click on the box until it's empty (no black checkmark), then click apply, then in the new window, answer "do this for all files and subdirectories".
Close "properties" and check again.
IF the Attribute field is cleared (read-only unchecked), you can re-apply the Patcher, this time it will work.
For those who get black windows when launching Patcher-1, the best thing to do is to uninstall, clear the "planetbase" entry with regedit, and then properly reinstall.
Then check the attributes of files and directories for the possibility of overwriting (uncheck "read-only" in the properties) until overwriting is allowed in all folders and files of the game, then you can run Mod Patcher.

### **3) Addresses of directories and files are not in English.**
If you do not have a Steam version of the game: if the file location contains letters other than English (for example, Russian letters), experiment with installing the game in another directory without long file addresses and only English letters in the names.

### **4) Antivirus or operating system settings.**
Occasionally it happens that an antivirus, some program or operating system interrupts the execution of programs for working with mods.
Check your antivirus settings and disable all other programs while patching.
Try patching again and make sure the patching process is complete.
Perhaps the operating system or some kind of antivirus program is preventing the Patcher from doing its job normally.
When opening the file, give all permissions in the operating system, make it run as administrator.

**Comment by NeoRider7** [comment]
### _Now there are 2 different engines on which it is possible to create and work with mods in the Planetbase game._
To work with mods in the Planetbase game, you need to choose one of the two currently existing engines for working with mods.
Mods created on one engine do not work on another. And vice versa.
Many mods created on one engine have their own copy of the mod to work in another engine.

Perhaps some of your mods did not start due to the fact that these mods were from a different mod engine?

As a last resort, if you can't run mods in one mod engine, then try running similar mods in another mod engine. ;-)

___________________
First, in 2016, [JPFarias](https://www.nexusmods.com/planetbase/users/19987409?tab=user+files) created the first modding engine.
This method of installing mods requires the initial installation of the [Patcher](https://www.nexusmods.com/planetbase/mods/1) and [Redirector](https://www.nexusmods.com/planetbase/mods/3).

Then, in 2020, [Tahvohck](https://github.com/Tahvohck/Planetbase-Mods) created his own engine for creating mods for the Planetbase game.
1) Mods created on the Tahvohck engine do not require Patcher and Redirector. However, it requires the installation of other software: "Unity Mod Manager Configuration" + "Planetbase Utilities".
2) Description from Tahvohck of the features of his platform and why he created it https://github.com/Tahvohck/Planetbase-Mods
3) Unity Mod Manager Configuration https://www.nexusmods.com/planetbase/mods/43
4) Planetbase Utilities https://www.nexusmods.com/planetbase/mods/45
5) Examples of mods working on the Tahvohck engine:
5.1) Mod 2.1: AutoConnections ReManaged https://www.nexusmods.com/planetbase/mods/46
5.2) Mod 2.2: Building Aligner ReManaged https://www.nexusmods.com/planetbase/mods/47
5.3) Mod 2.3: ComponentManager https://www.nexusmods.com/planetbase/mods/52
5.4) Mod 2.4: AlmostNoSpares Remake https://www.nexusmods.com/planetbase/mods/53

A more complete list of mods for both mod engines can be found in this guide: **Guide "List of Mods (and mod engines) for Planetbase":** https://steamcommunity.com/sharedfiles/filedetails/?id=1981754832
And the most up-to-date list of mods and engines can be found on NexusMods:  https://www.nexusmods.com/planetbase/mods/
