### ISSUE TITLE
Installation ZIP Reported To Contain Virus

### ISSUE THREAD

**Issue by tparikka** [solidDoWant/Planetbase-Framework#6]
Windows Defender detects the ZIP hosted at NexusMods as containing Trojan:Win32/Fuery.C!cl.

**Comment by solidDoWant** [comment]
I'm getting the same thing when I build the executable - not sure why, but it appears to be a false positive. I'm guessing it's because it modifies an executable that's not signed by me. If you're concerned about a trojan, I'd recommend you take a look at the source and compile it yourself. I'll do some research to see if I can figure out why it's being marked as a virus.

**Comment by solidDoWant** [comment]
Microsoft is no longer flagging the file as a virus, but SecureAge APEX and Trapmine are (https://www.virustotal.com/gui/file/4c4537e18055c68fc2a01fa505d6ecfa2ad913712c911aeb6ce532c16a7ed96b/detection). I've submitted the file to SecureAge for analysis but unfortunately I don't see a place to report a false positive to Trapmine. I'll be closing the ticket after I hear back from SecureAge.

**Comment by solidDoWant** [comment]
SecureAge cleared the file as a false positive. Closing issue.
